---
version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
      timezone: Europe/London
      time: "06:00"
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      timezone: Europe/London
      time: "06:00"
    labels:
      - dependencies
