---
version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
