---
version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: cron
      cronjob: 30 6 * * *
      timezone: Europe/London
    cooldown:
      default-days: 7
      semver-minor-days: 9
      semver-major-days: 11
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: cron
      cronjob: 30 6 * * *
      timezone: Europe/London
    cooldown:
      default-days: 7
      semver-minor-days: 9
      semver-major-days: 11
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directories:
      - .github/actions/*
      - /
    schedule:
      interval: cron
      cronjob: 30 6 * * *
      timezone: Europe/London
    cooldown:
      default-days: 7
      exclude:
        - ruby/setup-ruby
    labels:
      - dependencies
