---
PreCommit:

  ALL:
    problem_on_unmodified_line: warn

  RuboCop:
    enabled: true
    required_executable: bundle
    command: [bundle, exec, rubocop]
    problem_on_unmodified_line: report
    on_warn: fail

  TrailingWhitespace:
    enabled: true

  FileEncoding:
    description: Check text files are valid UTF-8
    enabled: true
    exclude: _spec/BBC/test_data/*

  SingleNewlineAtEof:
    description: Check text files end with a single newline
    enabled: true

  Copyright:
    description: Check copyright notices are present and updated
    enabled: true
