---
require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80

Metrics:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

RSpec/ExampleLength:
  Enabled: false
