require: rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 80

Metrics:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

RSpec/ExampleLength:
  Max: 8
