---
name: CI
on:
  push:
    branches-ignore: dependabot/**
  pull_request:
  schedule:
    - cron: '30 12 * * 5'

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruby and bundle
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Node packages
        run: npm ci

      - name: Cppcheck package
        run: sudo apt-get install cppcheck

      - name: Lint
        run: |
          bundle exec rake jshint
          bundle exec rubocop --format github
          bundle exec rake cppcheck

  overcommit:
    name: Overcommit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and sign
        run: |
          sudo gem install overcommit --no-document
          overcommit --sign
          overcommit --sign pre-commit

      - name: Run hooks
        env:
          GIT_AUTHOR_NAME: Dummy
          GIT_AUTHOR_EMAIL: dummy@example.com
          SKIP: RSpec,RuboCop
        run: overcommit --run

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependencies
        uses: ./.github/actions/dependencies

      - name: Build, test and proof
        run: |
          bundle exec rake compile
          bundle exec rspec
          bundle exec rake proof
