---
name: Diff PR output comment
on:
  workflow_run:
    workflows:
      - Diff PR output
    types:
      - completed

permissions:
  actions: read
  pull-requests: write

jobs:
  comment:
    name: Diff PR output comment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Fetch data
        uses: actions/download-artifact@v5
        with:
          name: data
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add PR comment with diff result
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs')
            const diffresult = fs.readFileSync('diffresult', 'utf8')
            const pr_number = Number(fs.readFileSync('pr_number'))
            var comment = "This PR does not change the generated site."
            if(diffresult.length > 0)
            {
              comment =
                "This PR changes the generated site:\n\n" +
                "<details><summary>Diff</summary>\n\n```\n" + diffresult +
                "```\n</details>"
            }
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
            })
            const existing = comments.find(
              comment => comment.user.id === 41898282 // Actions User
            )
            if(existing)
            {
              await github.rest.issues.updateComment({
                comment_id: existing.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment,
              })
            }
            else
            {
              await github.rest.issues.createComment({
                issue_number: pr_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment,
              })
            }
