---
name: Diff PR output comment
on:
  workflow_run:
    workflows:
      - Diff PR output
    types:
      - completed

jobs:
  comment:
    name: Diff PR output comment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Fetch data
        # Fetch manually via API as download-artifact doesn't support this yet
        # https://github.com/actions/download-artifact/issues/3
        uses: actions/github-script@v6
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            })
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "data"
            })[0]
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            })
            const fs = require('fs')
            fs.writeFileSync('${{github.workspace}}/data.zip',
                             Buffer.from(download.data))

      - name: Unzip data
        run: unzip data.zip

      - name: Add PR comment with diff result
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const diffresult = fs.readFileSync('diffresult', 'utf8')
            const pr_number = Number(fs.readFileSync('pr_number'))
            var comment = "This PR does not change the generated site."
            if(diffresult.length > 0)
            {
              comment =
                "This PR changes the generated site:\n\n" +
                "<details><summary>Diff</summary>\n\n```\n" + diffresult +
                "```\n</details>"
            }
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
            })
            const existing = comments.find(
              comment => comment.user.id === 41898282 // Actions User
            )
            if(existing)
            {
              await github.rest.issues.updateComment({
                comment_id: existing.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment,
              })
            }
            else
            {
              await github.rest.issues.createComment({
                issue_number: pr_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment,
              })
            }
